# core/__init__.py
from .version_manager import (
    VersionManager,
    SyncStatus,
    SyncState,
    ConflictInfo,
    InstallResult,
    PublishResult,
    # 模块级工具函数
    parse_version,
    compare_versions,
    version_gte,
    version_lte,
    version_gt,
    version_lt,
    version_eq,
    matches_skill,
    matches_software_version,
    version_distance,
    select_best_match,
    compare_skill_dirs,
    detect_layer_conflicts,
    LAYER_PRIORITY,
)

__all__ = [
    "VersionManager",
    "SyncStatus",
    "SyncState",
    "ConflictInfo",
    "InstallResult",
    "PublishResult",
    "parse_version",
    "compare_versions",
    "version_gte",
    "version_lte",
    "version_gt",
    "version_lt",
    "version_eq",
    "matches_skill",
    "matches_software_version",
    "version_distance",
    "select_best_match",
    "compare_skill_dirs",
    "detect_layer_conflicts",
    "LAYER_PRIORITY",
]
